Repository hashicorp/vscode-hcl, pull requests merged in 2022-11, with the labels that each got.

#162 Add Sentinel to telemetry
  src/common.ts
Labels: enhancement

#173 Readme: Add section to mention telemetry
  README.md
Labels: documentation

#174 Update HCL icon
  assets/HashiCorp_Icon_Black_RGB.svg
  assets/HashiCorp_Icon_White_RGB.svg
Labels: bug

#178 Polyfill path module
  package-lock.json
  package.json
  webpack.config.js
Labels: bug

#179 Add CI step to publish extension to OpenVSX
  .github/workflows/publish.yml
Labels: ci

#180 Add CI test step for PRs
  .github/workflows/test.yml
  .prettierignore
Labels: ci
